version: "3.6"
services:
  graphql-engine:
    image: hasura/graphql-engine:v2.36.1
    container_name: hasura-gql-engine
    restart: always
    ports:
      - 8081:8080
    environment:
      HASURA_GRAPHQL_DATABASE_URL: postgresql://postgres:p@srv/bets
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true"
      HASURA_GRAPHQL_DEV_MODE: "true"
